# Using the latest golang Docker image within the GitLab runner.
image: golang:latest

stages:
  - test

# Run the tests within *_test.go files. Uses verbose output and race condition flags.
run-tests:
  stage: test
  script:
    - go test -v -race ./...
