# Using the latest golang Docker image within the GitLab runner.
image: golang:latest

stages:
  - test

# Naming is arbitrary, 'format' defines the test stage for formatting, vetting (finding useless code and suspicious constructs
# through examining source code), and running the tests defined within the _test.go file(s).
run-tests:
  stage: test
  script:
    - go test -v -race ./...
