apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dummy-api
  name: api-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dummy-api
  type: NodePort
status:
  loadBalancer: {}
